### PR TITLE
brapi hackathon (move to openapi from swagger 2.0)

### PR DESCRIPTION
**Pull request by robkooper**
This contains the work from the hackathon. The main part is that BRAPI switched to openapi 3.0 and the code generator no longer works with this. This now uses the connexion libraries to use the brapi.yaml file to create the then endpoints automagically.

To implement new endpoints you will need to create a file in `/api/` with the name of the endpoint, for example `/calls/` is now find in /api/calls.py. For GET function without a name the function in the file has to be called `search()` for a GET with an ID it is called `get()`. See files in /api/ for more details.

### CODE REVIEW

**Comment by robkooper** [comment]
We should first merge #20 into this pull request to simplify the code base (or it can be merged into master after wards).

**Review by Chris-Schnaufer — APPROVED** [review]

**Comment by tcnichol** [comment]
Could I get instructions on how to run this locally?

**Comment by tcnichol** [comment]
I seem to be unable to connect to betydb and not sure what to change.

**Comment by dlebauer** [comment]
Did you see the readme on the openapi branch?

_______________________
David LeBauer
Director of Data Sciences
Arizona Experiment Station
THE UNIVERSITY OF ARIZONA

Bioscience Research Labs, 207
1230 N Cherry Ave | Tucson, AZ 85721
Office: 520-621-4381
dlebauer@email.arizona.edu

(sent from my phone - please pardon brevity and typos)


________________________________

**Comment by tcnichol** [comment]
@dlebauer thanks i was not using the right command to start up bety

looks good, marking both approved.

**Review by tcnichol — APPROVED** [review]
As far as I can tell this is fine. Marking approved.

**Pull request merged**
