### PR TITLE
Issue 583/clean up yaml

### PR DESCRIPTION
**Pull request by tcnichol**
Unused paths should be removed from the yaml file. A brapi_complete.yaml contains all paths.

### CODE REVIEW

**Comment by max-zilla** [comment]
Changes seem OK at a glance but the diff is massive, have you deployed this to see what the swagger doc looks like?

**Comment by tcnichol** [comment]
I will check using swagger locally and compare.

**Comment by tcnichol** [comment]
I checked locally against brapi-dev by running swagger locally. This should be fixed now.

**Comment by max-zilla** [comment]
Can you change this to be a PR against develop branch (create develop from master if it doesnt exist) and push to brapi-dev on kubernetes so we can compare.

**Comment by tcnichol** [comment]
I may have some deprecated methods left in, so I will check this carefully myself. If anyone else can check, let me know.

**Comment by max-zilla** [comment]
@max-zilla will check this and we can merge soon.

**Pull request merged**
